language: node_js

node_js:
  - 13

sudo: false

cache:
  yarn: true

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install

script:
  - yarn run test
